"""Add load test tables

Revision ID: 330ae1de6799
Revises: 604e8674793f
Create Date: 2025-11-26 09:22:56.943511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "330ae1de6799"
down_revision: Union[str, None] = "604e8674793f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "load_test_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("oas_spec", sa.Text(), nullable=True),
        sa.Column("oas_url", sa.String(length=2048), nullable=True),
        sa.Column("test_type", sa.String(length=50), nullable=False),
        sa.Column("concurrent_users", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("requests_per_second", sa.Integer(), nullable=True),
        sa.Column("endpoint_path", sa.String(length=512), nullable=True),
        sa.Column("endpoint_method", sa.String(length=10), nullable=True),
        sa.Column("request_headers", sa.JSON(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=True),
        sa.Column("successful_requests", sa.Integer(), nullable=True),
        sa.Column("failed_requests", sa.Integer(), nullable=True),
        sa.Column("avg_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("min_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("max_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("p95_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("p99_response_time_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_load_test_runs_created_at", "load_test_runs", ["created_at"], unique=False)
    op.create_index("idx_load_test_runs_project_id", "load_test_runs", ["project_id"], unique=False)
    op.create_index("idx_load_test_runs_status", "load_test_runs", ["status"], unique=False)
    op.create_table(
        "load_test_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("load_test_run_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_path", sa.String(length=512), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("request_headers", sa.JSON(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_success", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["load_test_run_id"], ["load_test_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_load_test_results_created_at", "load_test_results", ["created_at"], unique=False)
    op.create_index("idx_load_test_results_is_success", "load_test_results", ["is_success"], unique=False)
    op.create_index("idx_load_test_results_run_id", "load_test_results", ["load_test_run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_load_test_results_run_id", table_name="load_test_results")
    op.drop_index("idx_load_test_results_is_success", table_name="load_test_results")
    op.drop_index("idx_load_test_results_created_at", table_name="load_test_results")
    op.drop_table("load_test_results")
    op.drop_index("idx_load_test_runs_status", table_name="load_test_runs")
    op.drop_index("idx_load_test_runs_project_id", table_name="load_test_runs")
    op.drop_index("idx_load_test_runs_created_at", table_name="load_test_runs")
    op.drop_table("load_test_runs")
    # ### end Alembic commands ###
